### ISSUE TITLE
Support a max_response_body_length option?

### ISSUE THREAD

**Issue by PragTob** [wojtekmach/req#419] opened 2024-10-10 12:28 UTC
:wave: 

Would there be some interest in having a `mac_response_body_length` option? Naturally I'm not sure if that should be req, finch or mint.

Of course, you can handle it locally (and/or maybe implement your own step). It seems like a nice thing that could be offered from my point of view when you want to protect yourself against surprisingly too big responses.

Then again, it's something we currently need so of course I'd like it :)

Thanks a lot for `req` and all your work!

**Comment by wojtekmach** [comment] 2024-10-10 12:35
Hey Toby, this is a duplicate of https://github.com/wojtekmach/req/issues/355, there's a tip there how you can do it today and if Finch exposes this, so would we!

**Closed by wojtekmach** 2024-10-10 12:35 UTC

**Comment by PragTob** [comment] 2024-10-10 16:08
@wojtekmach sorry I didn't search well enough before! Thanks for the pointer!
