### ISSUE TITLE
`retry`: Getting translated `:unprocessed` Mint error when using HTTP2

### ISSUE THREAD

**Issue by DaTrader** [wojtekmach/req#329] opened 2024-03-22 14:25 UTC
When using HTTP2, sometimes I get the Mint `:unprocessed` error, but in a translated form i.e. as a string that reads: `request was not processed by the server, which means that it's safe to retry on a different or new connection`

Besides the fact that it would be very helpful if `Req` handled this error and retried the request, the problem is exacerbated by the fact that the error is returned in the string message format and not in an the `{ :error, :unprocessed}` or similar. It was only by searching for this string in the Mint library source code on github that I've found what the error really was.

The Mint documentation mentions this error here: https://hexdocs.pm/mint/Mint.HTTP2.html#module-closed-connection

**Comment by wojtekmach** [comment] 2024-03-22 15:54
Are you using Req.request or Req.request!, with or without bang? Because the latter would translate the error indeed.

I was able to reproduce that the error is correctly returned:

```elixir
Mix.install([
  :bandit,
  :req
])

defmodule Main do
  def main do
    # silence logger since Bandit fails really loudly.
    Logger.configure(level: :emergency)

    pid = self()

    spawn(fn ->
      {:ok, bandit_pid} =
        Bandit.start_link(
          scheme: :http,
          port: 4000,
          startup_log: false,
          plug: fn conn, _ ->
            {Bandit.HTTP2.Adapter, _} = conn.adapter
            Plug.Conn.send_resp(conn, 200, "hello")
          end
        )

      send(pid, {:ready, bandit_pid})
      Process.sleep(:infinity)
    end)

    bandit_pid =
      receive do
        {:ready, bandit_pid} -> bandit_pid
      end

    req =
      Req.new(
        url: "http://localhost:4000",
        connect_options: [protocols: [:http2]]
      )

    Req.get!(req)
    Process.exit(bandit_pid, :kill)
    {:error, %Mint.HTTPError{reason: :unprocessed, module: Mint.HTTP2}} = Req.get(req)
    IO.puts(:ok)
  end
end

Main.main()
```

If Mint says it is safe to retry then yeah we should. I'm not yet sure how to cleanly solve it as the current design is we retry _transient_ errors which are responses of some particular 4xx/5xx codes and otherwise transport errors (though we don't match on exception struct name) with a couple of reasons atoms like :closed/:timeout/:econnrefused. The idea was all underlying adapters would return stuff like :closed. I'm not sure we should blindly add :unprocessed to the reason allowlist. Of course we can standardise this particular error in the Finch adapter but unsure about standardising into _what_ exactly.

cc @whatyouhide, any feedback very appreciated.

**Comment by whatyouhide** [comment] 2024-03-22 16:28
@wojtekmach this is a `Mint.HTTPError` so not a transport error (rather a protocol error). You should look at the HTTP errors and determine whether they're transient or not, and `:unprocessed` is.

**Comment by DaTrader** [comment] 2024-03-22 17:32
> Because the latter would translate the error indeed

Regardless of this particular issue, I'm not sure if this is an ok thing to do. Not-bang functions are not necessarily supposed to return error translations, but just avoid having the exceptions raised. Since here we have multiple depth levels at which something can go wrong, in my view you should let all error tuples bubble up and when necessarily wrap and thus bubble up as well any exception structures, and only optionally provide an interface for translating them as a convenience. Otherwise, we have an issue of of either one extreme or the other (a rescueable crash or a low level error string message for the end-user).

**Comment by wojtekmach** [comment] 2024-03-22 17:42
Just to be clear Req doesn't translate errors to string per se. As I shown in the example, they are returned as is. The translation, so to speak, happens when bang functions raise these errors, their Exception.message/1 callback gets called. In other words:

```elixir
iex(1)> raise %Mint.HTTPError{reason: :unprocessed, module: Mint.HTTP2}
** (Mint.HTTPError) request was not processed by the server, which means that it's safe to retry on a different or new connection
    iex:1: (file)
```

Sorry if stating the obvious but thought I'd mention this just so we are on the same page.

**Comment by DaTrader** [comment] 2024-03-22 17:43
But I am not invoking a bang function.

**Comment by wojtekmach** [comment] 2024-03-22 17:50
I see. I was able to reproduce expected behavior with non bang function. Please try to reproduce where it does not work as expected.

**Comment by DaTrader** [comment] 2024-03-22 18:03
I'll need to allocate a substantial amount of time for that, but shouldn't the focus be on having Req retry the request as suggested by Mint?

**Comment by wojtekmach** [comment] 2024-03-22 18:15
If there is a spot where allegedly errors are translated to string, which as far as I can tell is not happening per snippet above, even if Req retries these in the pathological case when you exhaust retries the error would be returned as is.

**Comment by DaTrader** [comment] 2024-03-22 18:20
I am not sure I am following. What exactly do you mean by exhausting retries? The error is returned because the connection was closed. If it is reopened on retry why should it end up in error again?

Actually, I'll go straight to the point. I am new to http2 and would obviously like this issue to disappear.  Is there anything I could in terms of configuration or anything at all for it not to occur? I no longer have the connection close header (since I switched to http2) and I'd really hate to go back to http1 because of all the performance gain with http2.

**Comment by wojtekmach** [comment] 2024-03-22 21:45
Yeah, nevermind, let's just focus on retrying this error by default.

> Is there anything I could in terms of configuration or anything at all for it not to occur?

You can specify a custom `retry: fn request, response_or_error`, for this particular error return `true`.

**Comment by danschultzer** [comment] 2024-03-23 01:15
I've seen this occasionally surfacing as well. I'm adding a conditional for this particular error to retry, as I want to depend on the default retry logic in `Req` in general, but it would be great if `Req` could handle it automatically.

**Comment by DaTrader** [comment] 2024-03-28 15:22
> Yeah, nevermind, let's just focus on retrying this error by default.
> 
> > Is there anything I could in terms of configuration or anything at all for it not to occur?
> 
> You can specify a custom `retry: fn request, response_or_error` which for this particular error would return `true`.

@wojtekmach Please review the code below (intended to be invoked universally for all requests, but still supporting the caller to define its own `:retry` option as I do in some places throughout my code.  

Thanks!

```elixir
  @retry_codes [ 408, 429, 500, 502, 503, 504]
  @retry_reasons [ :timeout, :econnrefused, :closed]

  # Enforces the use of the http2 protocol for better performance than the
  # Req's default http1.
  @spec enforce_http2( keyword()) :: keyword()
  defp enforce_http2( opts) do
    opts
    |> Keyword.update( :retry, lenient_retry( nil), &lenient_retry/1)
    |> Keyword.merge( [ connect_options: [ protocols: [ :http2]]])
  end

  @spec lenient_retry( nil | :safe_transient | :transient | retry_function) :: result
        when retry_function: ( Req.Request.t(), Req.Response.t() | { :error, any()} -> result),
             result: true | { :delay, non_neg_integer()} | false | nil
  defp lenient_retry( retry)

  defp lenient_retry( default) when default in [ nil, :safe_transient] do
    fn
      _request, %Mint.HTTPError{ reason: :unprocessed, module: Mint.HTTP2} ->
        true

      %{ method: method}, %Req.Response{ status: code} when method in [ :get, :head] and code in @retry_codes ->
        true

      %{ method: method}, %{ reason: reason} = e when
        method in [ :get, :head] and is_exception( e) and reason in @retry_reasons ->
        true

      _request, _response_or_error ->
        false
    end
  end

  defp lenient_retry( :transient) do
    fn
      _request, %Mint.HTTPError{ reason: :unprocessed, module: Mint.HTTP2} ->
        true

      _request, %Req.Response{ status: code} when code in @retry_codes ->
        true

      _request, %{ reason: reason} = e when is_exception( e) and reason in @retry_reasons ->
        true

      _request, _response_or_error ->
        false
    end
  end

  defp lenient_retry( retry) when is_function( retry, 2) do
    fn
      _request, %Mint.HTTPError{ reason: :unprocessed, module: Mint.HTTP2} ->
        true

      request, response_or_error ->
        retry.( request, response_or_error)
    end
  end

  defp lenient_retry( falsy) when falsy in [ nil, false] do
    falsy
  end
```

**Comment by wojtekmach** [comment] 2024-03-28 18:51
Closing in favour of #335.

**Closed by wojtekmach** 2024-03-28 18:51 UTC

**Comment by DaTrader** [comment] 2024-04-17 14:04
> Closing in favour of #335.

@wojtekmach Is it normal that the `Mint.HTTPError` still gets logged as such even after intercepting it with the code I wrote above and returning `true` there?

**Comment by DaTrader** [comment] 2024-04-17 15:21
Nope. Should I?

**Comment by DaTrader** [comment] 2024-04-17 15:24
I now see there have been some changes in this regard since 0.14.4. But nevertheless, shouldn't my code as listed above work with the 0.4.14 and in that regard is the error going to get logged anyway?

**Comment by DaTrader** [comment] 2024-04-18 07:43
> Req.HTTPError is only available on main at the moment.

I get that. But my question relates to the `0.4.14`.  As said above, my code (an anonymous function returned by the `lenient_retry/1` function) does get called by `Req` on `Mint.HTTPError` `:unprocessed`, and the function returns `true` to `Req`. However, `Req` still logs the error, so my question was if it logs it but retries as instructed by my anon function, or it logs it and does not retry despite the fact that it got `true` from my function.
